/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c5c6cf",
        "surface-variant": "#e2e2e2",
        "surface-bright": "#f9f9f9",
        "on-tertiary-fixed": "#281800",
        "on-secondary-fixed-variant": "#005144",
        "on-surface-variant": "#44474e",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#4edcc1",
        "on-secondary": "#ffffff",
        secondary: "#006b5b",
        "tertiary-container": "#3d2700",
        "on-background": "#1a1c1c",
        "inverse-surface": "#2f3131",
        "secondary-container": "#6ff9dc",
        "on-primary-container": "#8293b7",
        "surface-container-low": "#f3f3f3",
        "error-container": "#ffdad6",
        "surface-tint": "#4e5e80",
        "on-primary-fixed": "#081b39",
        "tertiary-fixed-dim": "#e7c18a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#5c4217",
        "tertiary-fixed": "#ffddaf",
        "on-error-container": "#93000a",
        "surface-container-high": "#e8e8e8",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        outline: "#75777e",
        "surface-dim": "#dadada",
        "on-secondary-fixed": "#00201a",
        tertiary: "#221400",
        "inverse-primary": "#b6c6ee",
        "secondary-fixed": "#6ff9dc",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#364767",
        "primary-fixed": "#d8e2ff",
        "surface-container": "#eeeeee",
        "primary-container": "#1a2b4a",
        background: "#f9f9f9",
        surface: "#f9f9f9",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-secondary-container": "#007261",
        "inverse-on-surface": "#f1f1f1",
        primary: "#031634",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        md: "6px",
      },
      fontFamily: {
        headline: ["Sora", "sans-serif"],
        body: ["DM Sans", "sans-serif"],
        label: ["DM Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
